#ifndef TENTRIS_QUERYRESULTSTATE_HPP
#define TENTRIS_QUERYRESULTSTATE_HPP

namespace tentris::http {
    enum ResultState {
        OK, UNPARSABLE, UNKNOWN_REQUEST, PROCESSING_TIMEOUT, SERIALIZATION_TIMEOUT, UNEXPECTED, SEVERE_UNEXPECTED,
    };
}

#endif //TENTRIS_QUERYRESULTSTATE_HPP
